# Generated by Django 4.2.16 on 2024-11-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_fist_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(""" 
            INSERT INTO store_collection (title)
            VALUES ('collection1')                  
        """, """ 
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
